[package]
name = "join"
version = "0.2.0"
edition = "2024"

[dependencies]
globset = "0.4.18"
clap = "4.5.52"

# Rust
syn = { version = "2.0.110", features = ["full", "visit-mut"] }
prettyplease = "0.2"
